FRAMEWORK_VERSION = "0.8.0"
DATABASE_SCHEMA_VERSION = "0.8.0"
RESEARCH_ENGINE_VERSION = "research-engine-v0.5"
VALIDATION_ENGINE_VERSION = "validation-engine-v0.6"
HISTORICAL_REPLAY_VERSION = "historical-replay-v0.6.3"
REPLAY_CONFIDENCE_VERSION = "replay-confidence-v0.6.3"
NOTIFICATION_ENGINE_VERSION = "notification-engine-v0.8"
PIT_READINESS_VERSION = "pit-readiness-v0.8-phase2"
HISTORICAL_COVERAGE_VERSION = "historical-coverage-v0.8-phase2"
PROVIDER_CALIBRATION_VERSION = "provider-calibration-v0.8-phase2"
PROVIDER_CONFLICT_VERSION = "provider-conflict-v0.8-phase2"
DATASET_CONFIDENCE_VERSION = "dataset-confidence-v0.8-phase2"


__all__ = [
    "DATABASE_SCHEMA_VERSION",
    "DATASET_CONFIDENCE_VERSION",
    "FRAMEWORK_VERSION",
    "HISTORICAL_COVERAGE_VERSION",
    "HISTORICAL_REPLAY_VERSION",
    "NOTIFICATION_ENGINE_VERSION",
    "PIT_READINESS_VERSION",
    "PROVIDER_CALIBRATION_VERSION",
    "PROVIDER_CONFLICT_VERSION",
    "REPLAY_CONFIDENCE_VERSION",
    "RESEARCH_ENGINE_VERSION",
    "VALIDATION_ENGINE_VERSION",
]
