FRAMEWORK_VERSION = "0.7.1"
DATABASE_SCHEMA_VERSION = "0.7.0"
RESEARCH_ENGINE_VERSION = "research-engine-v0.5"
VALIDATION_ENGINE_VERSION = "validation-engine-v0.6"
HISTORICAL_REPLAY_VERSION = "historical-replay-v0.6.3"
REPLAY_CONFIDENCE_VERSION = "replay-confidence-v0.6.3"


__all__ = [
    "DATABASE_SCHEMA_VERSION",
    "FRAMEWORK_VERSION",
    "HISTORICAL_REPLAY_VERSION",
    "REPLAY_CONFIDENCE_VERSION",
    "RESEARCH_ENGINE_VERSION",
    "VALIDATION_ENGINE_VERSION",
]
